### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by GBardis** [AtomLinter/linter-tslint#155]
Argument to `path.dirname` must be a string
```
Object.dirname (/usr/share/atom/resources/app.asar/src/electron-shims.js:9:10)
<unknown> (/home/gdev/.atom/packages/linter-tslint/lib/main.js:232:50)
Object.<anonymous> (/home/gdev/.atom/packages/linter-tslint/lib/main.js:246:9)
undefined.next (null:null:null)
step (/home/gdev/.atom/packages/linter-tslint/lib/main.js:7:273)
```

**Comment by Arcanemagus** [comment]
@Xapphire13 Although Linter is _supposed_ to not trigger on _never_ saved buffers, somehow we still get situations where `textEditor.getPath()` still returns undefined. This can probably be fixed by putting a check for that [here](https://github.com/AtomLinter/linter-tslint/blob/v1.0.0/lib/main.js#L203).

**Comment by Xapphire13** [comment]
Working on it =]. I'll add specs for this case too
