### ISSUE TITLE
Single quote option

### ISSUE THREAD

**Issue by DonSanto** [AtomLinter/linter-tslint#34]
There should be a settings option for choosing to use single quote character instead of double quote character.

![image](https://cloud.githubusercontent.com/assets/1021604/11086488/e36137e0-8851-11e5-85b3-5e35418bc2ab.png)

**Comment by fresc81** [comment]
You can specify tslint options (including the quote characters) in a json file located in the root folder of your project. Check the docs for the tslint project. Here is a sample config file including the possible options:
https://github.com/palantir/tslint/blob/master/docs/sample.tslint.json

**Comment by DonSanto** [comment]
Thank you for your reply. Yes, I know that you can do that. However, I would prefer having these options as settings on the plugin so that my developing environment always behaves the same in all projects on all computers instead of having to add the same config file to every project just to have consistency. That would be great :)

**Comment by Arcanemagus** [comment]
You _really_ should be storing your linter configuration with the project, in any case if you don't have a configuration file in the specific project the `tslint` program should search all parents of the current directory, so you should be able to put a common configuration in your home directory (if all projects are under that).

Marking this as closed since this _really_ isn't the proper place to do that as @fresc81 already pointed out.

**Comment by t7yang** [comment]
but what if I want to make it totally portable, so pls at least make it read the tslint.json from .atom folder.

**Comment by Arcanemagus** [comment]
@t7yang Read the earlier comments, your linter configuration for a project should live with the project.
