### ISSUE TITLE
Dont't warn trailing whitespace on editing line

### ISSUE THREAD

**Issue by techird** [AtomLinter/linter-tslint#47]
Every time I enter a new line, the linter keep poping up a warn for trailing whitespaces.

That's annoying. That's will be nice if this miss in the editing line.

![image](https://cloud.githubusercontent.com/assets/1901286/12318990/c45e7b54-bad9-11e5-9e7e-53bbaea82219.png)

**Comment by Arcanemagus** [comment]
You should probably just increase the delay before linting as you type in the [Linter](https://github.com/atom-community/linter) package's settings. Plugins like this are just mean to forward on messages from the linter they work with, and `tslint` doesn't know where you are currently working on :wink:.

**Comment by techird** [comment]
Thanks a lot!

**Comment by Arcanemagus** [comment]
If you _really_ want that feature, you would need to check for that specific message, then check whether it matched the current line of the latest cursor (since Atom can have multiple), and if so ignore it. If you want to put together a PR that handles that (behind an option, defaulting to disabled) I wouldn't be opposed to merging that in.
